services:
  db:
    image: postgres:16
    container_name: repetition7-db
    environment:
      POSTGRES_DB: repetition7
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d repetition7"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: repetition7-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/repetition7
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: strongpassword

      APP_SECURITY_USERNAME: admin
      APP_SECURITY_PASSWORD: strong